[mA1]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mA2]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mA3]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mA4]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mA5]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mA6]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mA7]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mA8]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mA9]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mB1]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mB2]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mB3]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mB4]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mB5]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mB6]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mB7]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mB8]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mB9]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mC1]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mC2]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mC3]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mC4]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mC5]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mC6]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mC7]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mC8]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mC9]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mD1]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mD2]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mD3]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mD4]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mD5]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mD6]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mD7]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mD8]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mD9]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mE1]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mE2]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mE3]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mE4]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mE5]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mE6]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mE7]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mE8]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mE9]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mF1]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mF2]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mF3]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mF4]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mF5]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mF6]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mF7]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mF8]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mF9]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mG1]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mG2]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mG3]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mG4]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mG5]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mG6]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mG7]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mG8]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mG9]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mH1]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mH2]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mH3]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mH4]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mH5]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mH6]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mH7]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mH8]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mH9]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mI1]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mI2]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mI3]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mI4]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mI5]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mI6]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mI7]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mI8]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures

[mI9]
Measure=CALC
Formula=0
Substitute="0":" "
UpdateDivider=-1
Group=cellMeasures
