[A1]
Meter=STRING
MeterStyle=styleCell
X=(#majorGap# + (#cellSize# / 2))r
Y=(#majorGap# + (#cellSize# / 2))r

[A2]
Meter=STRING
MeterStyle=styleCell

[A3]
Meter=STRING
MeterStyle=styleCell

[A4]
Meter=STRING
MeterStyle=styleCell | styleHGap

[A5]
Meter=STRING
MeterStyle=styleCell

[A6]
Meter=STRING
MeterStyle=styleCell

[A7]
Meter=STRING
MeterStyle=styleCell | styleHGap

[A8]
Meter=STRING
MeterStyle=styleCell

[A9]
Meter=STRING
MeterStyle=styleCell

[B1]
Meter=STRING
MeterStyle=styleCell | styleNewRow

[B2]
Meter=STRING
MeterStyle=styleCell

[B3]
Meter=STRING
MeterStyle=styleCell

[B4]
Meter=STRING
MeterStyle=styleCell | styleHGap

[B5]
Meter=STRING
MeterStyle=styleCell

[B6]
Meter=STRING
MeterStyle=styleCell

[B7]
Meter=STRING
MeterStyle=styleCell | styleHGap

[B8]
Meter=STRING
MeterStyle=styleCell

[B9]
Meter=STRING
MeterStyle=styleCell

[C1]
Meter=STRING
MeterStyle=styleCell | styleNewRow

[C2]
Meter=STRING
MeterStyle=styleCell

[C3]
Meter=STRING
MeterStyle=styleCell

[C4]
Meter=STRING
MeterStyle=styleCell | styleHGap

[C5]
Meter=STRING
MeterStyle=styleCell

[C6]
Meter=STRING
MeterStyle=styleCell

[C7]
Meter=STRING
MeterStyle=styleCell | styleHGap

[C8]
Meter=STRING
MeterStyle=styleCell

[C9]
Meter=STRING
MeterStyle=styleCell

[D1]
Meter=STRING
MeterStyle=styleCell | styleNewRow | styleVGap

[D2]
Meter=STRING
MeterStyle=styleCell

[D3]
Meter=STRING
MeterStyle=styleCell

[D4]
Meter=STRING
MeterStyle=styleCell | styleHGap

[D5]
Meter=STRING
MeterStyle=styleCell

[D6]
Meter=STRING
MeterStyle=styleCell

[D7]
Meter=STRING
MeterStyle=styleCell | styleHGap

[D8]
Meter=STRING
MeterStyle=styleCell

[D9]
Meter=STRING
MeterStyle=styleCell

[E1]
Meter=STRING
MeterStyle=styleCell | styleNewRow

[E2]
Meter=STRING
MeterStyle=styleCell

[E3]
Meter=STRING
MeterStyle=styleCell

[E4]
Meter=STRING
MeterStyle=styleCell | styleHGap

[E5]
Meter=STRING
MeterStyle=styleCell

[E6]
Meter=STRING
MeterStyle=styleCell

[E7]
Meter=STRING
MeterStyle=styleCell | styleHGap

[E8]
Meter=STRING
MeterStyle=styleCell

[E9]
Meter=STRING
MeterStyle=styleCell

[F1]
Meter=STRING
MeterStyle=styleCell | styleNewRow

[F2]
Meter=STRING
MeterStyle=styleCell

[F3]
Meter=STRING
MeterStyle=styleCell

[F4]
Meter=STRING
MeterStyle=styleCell | styleHGap

[F5]
Meter=STRING
MeterStyle=styleCell

[F6]
Meter=STRING
MeterStyle=styleCell

[F7]
Meter=STRING
MeterStyle=styleCell | styleHGap

[F8]
Meter=STRING
MeterStyle=styleCell

[F9]
Meter=STRING
MeterStyle=styleCell

[G1]
Meter=STRING
MeterStyle=styleCell | styleNewRow | styleVGap

[G2]
Meter=STRING
MeterStyle=styleCell

[G3]
Meter=STRING
MeterStyle=styleCell

[G4]
Meter=STRING
MeterStyle=styleCell | styleHGap

[G5]
Meter=STRING
MeterStyle=styleCell

[G6]
Meter=STRING
MeterStyle=styleCell

[G7]
Meter=STRING
MeterStyle=styleCell | styleHGap

[G8]
Meter=STRING
MeterStyle=styleCell

[G9]
Meter=STRING
MeterStyle=styleCell

[H1]
Meter=STRING
MeterStyle=styleCell | styleNewRow

[H2]
Meter=STRING
MeterStyle=styleCell

[H3]
Meter=STRING
MeterStyle=styleCell

[H4]
Meter=STRING
MeterStyle=styleCell | styleHGap

[H5]
Meter=STRING
MeterStyle=styleCell

[H6]
Meter=STRING
MeterStyle=styleCell

[H7]
Meter=STRING
MeterStyle=styleCell | styleHGap

[H8]
Meter=STRING
MeterStyle=styleCell

[H9]
Meter=STRING
MeterStyle=styleCell

[I1]
Meter=STRING
MeterStyle=styleCell | styleNewRow

[I2]
Meter=STRING
MeterStyle=styleCell

[I3]
Meter=STRING
MeterStyle=styleCell

[I4]
Meter=STRING
MeterStyle=styleCell | styleHGap

[I5]
Meter=STRING
MeterStyle=styleCell

[I6]
Meter=STRING
MeterStyle=styleCell

[I7]
Meter=STRING
MeterStyle=styleCell | styleHGap

[I8]
Meter=STRING
MeterStyle=styleCell

[I9]
Meter=STRING
MeterStyle=styleCell